# Generated by Django 2.1.2 on 2018-11-23 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venter', '0005_auto_20181120_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='authority_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='venter.Authorities'),
        ),
    ]
