# Generated by Django 2.2 on 2019-07-20 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0014_location_str_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='pixel_x',
        ),
        migrations.RemoveField(
            model_name='location',
            name='pixel_y',
        ),
    ]
